trigger:
- main  # Trigger pipeline ketika ada perubahan pada branch main

pool:
  name: 'Default'

steps:
  # Checkout code dari repository
  - task: Checkout@1
    displayName: Checkout Code

  # Membangun dan Mendorong Docker Image
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: 'docker'  # Service connection Docker Hub
      repository: 'anisarahmah/react'  # Nama repository di Docker Hub
      command: 'buildAndPush'