trigger:
- main  # Trigger pipeline ketika ada perubahan pada branch main

stages:
- stage: BuildAndPush
  jobs:
    - job: BuildAndPushJob
      steps:
        # Checkout code dari repository
        - task: Checkout@1
          displayName: Checkout Code

        # Membangun Docker Image
        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            command: 'build'
            containerRegistry: $(dockerRegistry)
            repository: $(containerRegistry)/$(imageName)
            dockerfile: '**/Dockerfile'  # Pastikan Dockerfile ada di proyekmu
            tags: $(tag)

        # Push Docker Image ke Docker Hub
        - task: Docker@2
          displayName: Push Docker Image
          inputs:
            command: 'push'
            containerRegistry: $(dockerRegistry)
            repository: $(containerRegistry)/$(imageName)
            tags: $(tag)
