trigger:
- main  # Trigger pipeline ketika ada perubahan pada branch main

stages:
- stage: BuildAndPush
  jobs:
    - job: BuildAndPushJob
      steps:
        # Checkout code dari repository
        - task: Checkout@1
          displayName: Checkout Code

        # Membangun Docker Image
        - task: Docker@2
          inputs:
            containerRegistry: 'docker'
            repository: 'anisarahmah/react'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest

