# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'anisarahmah/react'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
