trigger: none

pool:
  vmImage: Default

steps:
# Checkout code dari repository GitHub
- task: Checkout@1
  inputs:
    repository: 'self'
    clean: true

# Setup Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '22.10.0'

# Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Cache Node.js dependencies untuk mempercepat build selanjutnya
- task: CacheBeta@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'  # Cache berdasarkan package-lock.json
    path: $(Pipeline.Workspace)/.npm
    cacheHitVar: NpmCacheRestored
  displayName: 'Cache Node.js Dependencies'

# Dependency check dengan OWASP
#- task: dependency-check-build-task@6
#  inputs:
#    format: 'HTML'
#    uploadReports: true
#    reportDirectory: '$(Build.ArtifactStagingDirectory)/dependency-check'
#    reportFilename: 'dependency-check-report.html'
#    scanPath: '$(Build.SourcesDirectory)/src'  # Lokasi untuk pemindaian dependensi
#    cvssFailureThreshold: '7.0'
#    uploadSARIFReports: true
#    projectName: ''

# Linting dengan fix
- script: |
    npx eslint . --fix --format json -o eslint-report.json
  displayName: 'Run ESLint with Fix and Report'

# Publish report
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'eslint-report.json'
    ArtifactName: 'ESLint Report'
  displayName: 'Publish ESLint Report'

# Kirim email jika linting gagal
- task: SendEmail@1
  condition: eq(variables['Build.Tasks.Failed'], 'Run ESLint with Fix and Report')
  inputs:
    To: 'nisarah1220@gmail.com'
    From: 'nisarah1220@gmail.com'
    Subject: 'Code Quality Check Failed'
    Body: |
      Hi Team,
            The code quality check has failed. Please review the logs.
    BodyAsHtml: false
    AddAttachment: false
    SmtpPort: 587
    SmtpServer: smtp.gmail.com
    SmtpUsername: nisarah1220@gmail.com
    SmtpPassword: $(mailPass)
    UseSSL: true
