trigger:
- master

pool:
  name: 'Default'  # Gunakan pool agen yang sesuai dengan self-hosted agent Anda

steps:
# Checkout code dari repository GitHub
- task: Checkout@1
  inputs:
    repository: 'self'  # Repository default (GitHub)
    clean: true  # Membersihkan file kerja sebelum checkout

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '22.10.0'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npx eslint . --fix
  displayName: 'Run ESLint for Code Quality'
  continueOnError: false

- task: SendEmail@1
  inputs:
    To: 'nisarah1220@gmail.com'
    From: 'nisarah1220@gmail.com'
    Subject: 'Code Quality Check Failed'
    Body: |
      Hi Team,
            The code quality check has failed. Please review the logs.
    BodyAsHtml: false
    AddAttachment: false
    SmtpPort: 587
    SmtpServer: smtp.gmail.com
    SmtpUsername: nisarah1220@gmail.com
    SmtpPassword: $(mailPass)
    UseSSL: false