trigger:
- master

pool:
  name: 'Default'  # Gunakan pool agen yang sesuai dengan self-hosted agent Anda

steps:
# Checkout code dari repository GitHub
- task: Checkout@1
  inputs:
    repository: 'self'  # Repository default (GitHub)
    clean: true  # Membersihkan file kerja sebelum checkout

- task: dependency-check-build-task@6
  inputs:
    projectName: 'belajar devops'  # Nama proyek Anda
    format: 'JSON'  # Format laporan, bisa juga 'JSON' atau 'XML'
    uploadReports: true  # Mengupload laporan ke pipeline
    scanPath: '$(Build.SourcesDirectory)/src'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '22.10.0'

- script: |
    npm install
    npx eslint .
  displayName: 'Run ESLint for Code Quality'
  continueOnError: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dependency-check-report'
    publishLocation: 'Container'

- script: |
    if [ -f "$(Build.ArtifactStagingDirectory)/dependency-check/dependency-check-report.html" ]; then
      echo "Build succeeded"
    else
      echo "Build failed"
      exit 1
    fi
  displayName: 'Fail Pipeline if Issues Found'
  continueOnError: false
