trigger:
- main  # Trigger pipeline ketika ada perubahan pada branch main

pool:
  name: 'Default'

steps:
  # Checkout code dari repository
  - task: Checkout@1
    displayName: Checkout Code

  # Build Docker Image
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      containerRegistry: 'docker'  # Ganti dengan nama Docker Registry Service Connection yang sesuai
      repository: 'anisarahmah/react'  # Nama repository Docker Hub
      command: 'build'  # Build image
      Dockerfile: '**/Dockerfile'  # Path ke Dockerfile
      tags: |
        $(Build.BuildId)

  # Push Docker Image ke Docker Hub
  - task: Docker@2
    displayName: Push Docker Image
    inputs:
      containerRegistry: 'docker'  # Ganti dengan nama Docker Registry Service Connection yang sesuai
      repository: 'anisarahmah/react'  # Nama repository Docker Hub
      command: 'push'  # Push image ke registry
      tags: |
        $(Build.BuildId)
        latest
